kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cicd-pipeline"
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/LEADSNGFS/ci-cd-pipeline-demo.git'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsFile
    type: JenkinsPipeline
